name: seim_canary
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  uuid: ^4.5.1
  bcrypt: 1.1.3
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  crypto: ^3.0.6
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  flutter:
    sdk: flutter
  intl: ^0.20.2
  fl_chart: ^0.65.0
  provider: ^6.1.1 # o la última versión estable


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
