// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnVKDopCShMunyUVCEDCFaOip5645gxng',
    appId: '1:57944217344:web:5fc2213118f97589be45e5',
    messagingSenderId: '57944217344',
    projectId: 'seim-b3fde',
    authDomain: 'seim-b3fde.firebaseapp.com',
    storageBucket: 'seim-b3fde.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApVsfphRt975V7NpNF0fJQe_iub-4R_qM',
    appId: '1:57944217344:android:e978fc7b56fe34ddbe45e5',
    messagingSenderId: '57944217344',
    projectId: 'seim-b3fde',
    storageBucket: 'seim-b3fde.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnVKDopCShMunyUVCEDCFaOip5645gxng',
    appId: '1:57944217344:web:a0564a925966eee2be45e5',
    messagingSenderId: '57944217344',
    projectId: 'seim-b3fde',
    authDomain: 'seim-b3fde.firebaseapp.com',
    storageBucket: 'seim-b3fde.firebasestorage.app',
  );
}
